# Netlify configuration for OptixDigitalAI

[build]
  command = "npm run build"   # Build command for Vite
  publish = "dist"            # Folder to deploy (Vite output)


# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # ensure all routes redirect to index.html


